<?php

namespace DLCompare\LoLApiBundle\Model;

use Doctrine\ORM\EntityRepository;

use DLCompare\LoLApiBundle\Entity\Champion;
use DLCompare\LoLApiBundle\Entity\Item;

/**
 * ChampionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChampionRepository extends EntityRepository
{
	public function getMainChampions(Item $item, $maxResults = 10)
	{
		$qb = $this->createQueryBuilder('c');
		$ex = $qb->expr();

		return $qb
			->addSelect('COUNT(c) AS HIDDEN usage')
			->leftJoin('c.participants', 'p')
			->leftJoin('p.items', 'i')
			->leftJoin('p.game', 'g')
			->where($ex->eq('i.id', $item->getId()))
			->andWhere($ex->gt('g.duration', 35 * 60))
            ->groupBy('c.id')
            ->orderBy('usage', 'DESC')
			->setMaxResults($maxResults)
			->getQuery()
			->execute()
		;		
	}

}
