<?php

namespace DLCompare\LoLApiBundle\Model;

use Doctrine\ORM\EntityRepository;

use DLCompare\LoLApiBundle\Entity\Champion;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{	
	public function countBansByBersion($version)
	{
		$qb = $this->createQueryBuilder('g');
		$ex = $qb->expr();

		$result = $qb
			->select('COUNT(b)')
			->leftJoin('g.bans', 'b')
			->where($ex->like('g.version', $ex->literal($version . '%')))
			->getQuery()
			->getSingleScalarResult()
		;

		return $result;
	}

	public function countBansByVersionByChampion($version, Champion $champion)
	{
		$qb = $this->createQueryBuilder('g');
		$ex = $qb->expr();

		$result = $qb
			->select('COUNT(b)')
			->leftJoin('g.bans', 'b')
			->where($ex->like('g.version', $ex->literal($version . '%')))
			->andWhere($ex->eq('b.id', $champion->getId()))
			->getQuery()
			->getSingleScalarResult()
		;

		return $result;
	}
}
