<?php

namespace DLCompare\LoLApiBundle\Model;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

use DLCompare\LoLApiBundle\Entity\Champion;
use DLCompare\LoLApiBundle\Entity\Participant;
use DLCompare\LoLApiBundle\Entity\Item;

/**
 * ParticipantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipantRepository extends EntityRepository
{
	public function countByVersion($version)
	{
		$qb = $this->createQueryBuilder('p');
		$ex = $qb->expr();

		$result = $qb
			->select('COUNT(p)')
			->leftJoin('p.game', 'g')
			->where($ex->like('g.version', $ex->literal($version . '%')))
			->getQuery()
			->getSingleScalarResult()
		;

		return $result;
	}

	public function countByVersionByChampion($version, Champion $champion)
	{
		$qb = $this->createQueryBuilder('p');
		$ex = $qb->expr();

		$result = $qb
			->select('COUNT(p)')
			->leftJoin('p.game', 'g')
			->leftJoin('p.champion', 'c')
			->where($ex->like('g.version', $ex->literal($version . '%')))
			->andWhere($ex->eq('c.id', $champion->getId()))
			->getQuery()
			->getSingleScalarResult()
		;

		return $result;
	}

	public function countByVersionByItem($version, Item $item)
	{
		$qb = $this->createQueryBuilder('p');
		$ex = $qb->expr();

		$result = $qb
			->select('COUNT(p)')
			->leftJoin('p.game', 'g')
			->leftJoin('p.items', 'i')
			->where($ex->like('g.version', $ex->literal($version . '%')))
			->andWhere($ex->eq('i.id', $item->getId()))
			->getQuery()
			->getSingleScalarResult()
		;

		return $result;
	}

	public function countByVersionByChampionByWin($version, Champion $champion)
	{
		$qb = $this->createQueryBuilder('p');
		$ex = $qb->expr();

		$result = $qb
			->select('COUNT(p)')
			->leftJoin('p.game', 'g')
			->leftJoin('p.champion', 'c')
			->where($ex->like('g.version', $ex->literal($version . '%')))
			->andWhere($ex->eq('c.id', $champion->getId()))
			->andWhere($ex->eq('p.winner', $ex->literal(1)))
			->getQuery()
			->getSingleScalarResult()
		;

		return $result;
	}

	public function countKillsByVersionByChampion($version, Champion $champion)
	{
		$qb = $this->createQueryBuilder('p');
		$ex = $qb->expr();

		$result = $qb
			->select('SUM(p.kills)')
			->leftJoin('p.game', 'g')
			->leftJoin('p.champion', 'c')
			->where($ex->like('g.version', $ex->literal($version . '%')))
			->andWhere($ex->eq('c.id', $champion->getId()))
			->getQuery()
			->getSingleScalarResult()
		;

		return $result;
	}

	public function countDeathsByVersionByChampion($version, Champion $champion)
	{
		$qb = $this->createQueryBuilder('p');
		$ex = $qb->expr();

		$result = $qb
			->select('SUM(p.deaths)')
			->leftJoin('p.game', 'g')
			->leftJoin('p.champion', 'c')
			->where($ex->like('g.version', $ex->literal($version . '%')))
			->andWhere($ex->eq('c.id', $champion->getId()))
			->getQuery()
			->getSingleScalarResult()
		;

		return $result;
	}

	public function countAssistsByVersionByChampion($version, Champion $champion)
	{
		$qb = $this->createQueryBuilder('p');
		$ex = $qb->expr();

		$result = $qb
			->select('SUM(p.assists)')
			->leftJoin('p.game', 'g')
			->leftJoin('p.champion', 'c')
			->where($ex->like('g.version', $ex->literal($version . '%')))
			->andWhere($ex->eq('c.id', $champion->getId()))
			->getQuery()
			->getSingleScalarResult()
		;

		return $result;
	}

	public function getGoldPerMinute($version, Champion $champion)
	{
		// gold
		$qb = $this->createQueryBuilder('p');
		$ex = $qb->expr();

		$gold = $qb
			->select('SUM(p.gold)')
			->leftJoin('p.game', 'g')
			->leftJoin('p.champion', 'c')
			->where($ex->like('g.version', $ex->literal($version . '%')))
			->andWhere($ex->eq('c.id', $champion->getId()))
			->getQuery()
			->getSingleScalarResult()
		;

		// minutes
		$qb = $this->createQueryBuilder('p');
		$ex = $qb->expr();

		$duration = $qb
			->select('SUM(g.duration)')
			->leftJoin('p.game', 'g')
			->leftJoin('p.champion', 'c')
			->where($ex->like('g.version', $ex->literal($version . '%')))
			->andWhere($ex->eq('c.id', $champion->getId()))
			->getQuery()
			->getSingleScalarResult()
		;

		return ($duration == 0)
			? 0
			: number_format(60 * $gold / $duration, 2)
		;
	}

	public function getCommonBuild(Champion $champion, $version, $start = 40, $end = 1000)
	{
		$sql = "
			SELECT sub.id AS id, sub.build, COUNT(sub.id) AS cpt FROM
			(
				SELECT p.id , GROUP_CONCAT(i.item_id) AS build FROM participant p 
				LEFT JOIN participant_items i ON i.participant_id = p.id 
				LEFT JOIN game g ON p.game_id = g.id
				LEFT JOIN champion c ON p.champion_id = c.id
				WHERE c.id = " . $champion->getId() . "
					AND g.version LIKE '". $version . "%'
					AND g.duration > " . $start * 60 . "
					AND g.duration < " . $end * 60 . "
				GROUP BY p.id 
				ORDER BY build DESC
			) AS sub
			GROUP BY sub.build
			ORDER BY cpt DESC
			LIMIT 1
		";	

		$rsm = new ResultSetMapping();
        $rsm->addScalarResult('id', 'id');
        $query  = $this->getEntityManager()->createNativeQuery($sql, $rsm);
        $result = $query->getResult();
        if(count($result) == 0) { return new Participant(); }

        return $this->findOneById($result[0]['id']);
	}
}

